### PR TITLE
Set wagmi v1.4.13 and viem v1.21.4 as dependencies

### LINKED ISSUE #236: [WIDGET] Create version compatible with wagmi v2
## Overview
**What?**
The `wagmi` library has released version 2 of their library which has [several breaking changes](https://wagmi.sh/react/guides/migrate-from-v1-to-v2). For projects that wish to take advantage of the new features of that major version would be good to have a Superfluid Widget version that supports that version of the library.

**How?**
Create a new version of the Widget NPM package (0.4.9?) that sets the peer dependency to be less than 2.0.0 for `wagmi` (to clearly indicate it does _not_ work with later versions.

Create a new major version of the Widget NPM package (v2.0.0, to keep the widget numbering the same as `wagmi`'s versioning), set the peer dependency to be at least `wagmi` v2.0.0, and update the Widget logic to properly pull the logic it needs.

Attempting to use the 0.4.8 version of the Superfluid Widget with `wagmi` >2.0.0 gives an error of 

```
./node_modules/@superfluid-finance/widget/dist/WidgetCore.js:9:0
Module not found: Package path ./connectors/injected is not exported from package /app/node_modules/wagmi (see exports field in /app/node_modules/wagmi/package.json)
```

(the "injected" connector is no longer at that code location), so it cannot just be used as-is.

**Why?**
That version [was released January 2024](https://github.com/wevm/wagmi/releases/tag/wagmi%402.0.1), and has had several months to stabilize and have security issues fixed. 

**Deadline:**
??

**UI/UX Design:**
`wagmi` is a business-logic library; no need for changes to the UI for this library update.

## Acceptance criteria
 - [ ] ...
 - [ ] Satisfies entire acceptance criteria
 - [ ] Consider communication & visibility
 - [ ] Code review is approved by at least 2 reviewers
 - [ ] Tested by Elvijs/QA & discovered bugs resolved
 - [ ] Documentation updated
 - [ ] Assignee/opened by merges PR
 - [ ] Automated E2E tests for happy path
 - [ ] Code is merged
 - [ ] Observability of critical user path
 - [ ] Steps to access code change as a user

## Links/Resources
 * https://wagmi.sh/core/guides/migrate-from-v1-to-v2
 * https://www.npmjs.com/package/wagmi

## Readiness criteria
- [ ] Descriptive title
- [ ] What?
- [ ] Why?
- [ ] How?
- [ ] Acceptance criteria complying with Definition of Done
- [ ] Estimate/Story points
- [ ] Deadline: If not a part of an epic
- [ ] Priority: Reflected as order on the board, walking the board from the top and right
- [ ] Assignee
- [ ] Labels
- [ ] Link to epic: If belonging to an epic
- [ ] A task is always a separate ticket/issue
- [ ] UI/UX Design (optional)
- [ ] Blockers/Prerequisites (optional): Use Zenhub blocked by/blocking feature

### PR DESCRIPTION
**Pull request by MidnightLightning**
The Superfluid Widget currently marks `wagmi` and `viem` as "peer dependencies" rather than "dependencies". The intent of a "peer dependency" is to indicate to the package manager that the other library is "good to have", but not essential for the running of the component. The Superfluid Widget pulls in the `wagmi` and `viem` functionality directly, so these should be marked as actual dependencies of the component.

Additionally, harmonized on one version of those third-party libraries (the `docs` folder had a separate version of them).

This change should fix #236 as it will allow the Superfluid Widget to continue to use `wagmi` v1 as long as it wants (package managers will present to the widget its own copy of the v1 version of the library), while projects that implement it can move on to other versions of `wagmi` if they so choose.

### CODE REVIEW

**Comment by kasparkallas** [comment]
Hey @MidnightLightning

I appreciate the effort.

> The intent of a "peer dependency" is to indicate to the package manager that the other library is "good to have", but not essential for the running of the component.

Sorry but this is not correct. A peer dependency not marked as optional is as much of an essential dependency as a regular dependency. Because the types of wagmi/viem are exposed in the widget's API then it's correct to make them peer dependencies.

So I don't think this is the correct solution... but I see what you're going for though... and understand the frustration. I can do a special release for this.

It's also probably possible to fix it with NPM overrides, NPM aliases or monkeypatching somehow, but it's a pain...

Did you try automatic installation of peer dependencies?

**Comment by MidnightLightning** [comment]
Oh, I forgot about the `wagmi` context that needs to be set; that would be a limiting factor for having `wagmi` be a dependency 🙈 If the project configured a "wagmi v2" provider, and put a Superfluid widget within that context, the widget would expect the provided context to be a different style, so likely wouldn't work even if it had a copy of the `wagmi` v1 code bundled with it.

So, the basic change here I think is the peer dependency needs to note that `wagmi` v2 is not supported, which will at least allow NPM to properly warn project developers when there's likely to be runtime incompatibilities with the Superfluid widget.

**Comment by kasparkallas** [comment]
Oh indeed, this is wrong in the widget package.json:
```
"viem": ">=1",
"wagmi": ">=1"
```

**Comment by MidnightLightning** [comment]
Thanks for updating the v0 version of the Superfluid widget to properly self-identify as needing a wagmi v1 environment. I'll close this request and attempt to get my own development environment working to be able to contribute the code changes needed to run within a wagmi v2 environment, as a potential new major version for the Superfluid widget.

**Pull request closed without merging**
