### PR TITLE
Adding docs

### PR DESCRIPTION
**Pull request by youssefea**
This is a pull request to add a docs folder to the widget repo. The folder contains a documentation based on MDX and Nextra including:

- Quickstart
- Description of the widget builder
- Description of how to integrate the widget in your app
- NFT Gating
- FAQ

This is a first version of the docs, and further updates will take place, especially as we move towards a new component of the product: being the stripe integration.

### CODE REVIEW

**Comment by vmichalik** [comment]
@kasparkallas @youssefea is this actually ready for review? what are we testing?

**Comment by youssefea** [comment]
@vmichalik it is not ready for review afaik. cc: @kasparkallas

**Comment by kasparkallas** [comment]
> @kasparkallas @youssefea is this actually ready for review? what are we testing?

Just a plug for very early feedback. Sorry, I guess it was too early... Removed for now.

This is the environment where things are shaping up:
image

**Comment by youssefea** [comment]
@vmichalik @kasparkallas This is ready for review. Deployment of the docs here: https://widget-docs-test.vercel.app/

**Review by philipandersson — APPROVED** [review]

**Comment by philipandersson** [comment]
@kasparkallas @tokdaniel If you want to review this do it asap. We are merging EOD.

**Comment by philipandersson** [comment]
@youssefea please sign commits https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits

**Pull request closed without merging**
